### ISSUE TITLE
Command 'plot_interactions'

### ISSUE THREAD

**Issue by MerjaElo** [James-Thorson/MIST#2]
Even with the example data I was unable to use the command 'plot_interactions' successfully but got the error message below:

Error in FormatC(Re(Eigen$values[p]), 3) : 
  could not find function "FormatC"

**Comment by James-Thorson** [comment]
This should be fixed now if you re-install MIST, could you please try and close this issue if it is solved?

**Comment by MerjaElo** [comment]
After re-installing MIST a little bit different (but related) error message:

Error in FormatC(abs(Im(Eigen$values[p])), 3) : 
  could not find function "FormatC"

**Comment by James-Thorson** [comment]
What function does that one occur in?

**Comment by MerjaElo** [comment]
The same one: plot_interactions

**Comment by James-Thorson** [comment]
Should be fixed now.

**Comment by MerjaElo** [comment]
Great! Thank you!
