### ISSUE TITLE
Command 'summarize'

### ISSUE THREAD

**Issue by MerjaElo** [James-Thorson/MIST#3]
Regarding the command 'summarize': 
I assume that B_pp_hat is the interaction matrix and Cov_pp_hat is the estimated covariance of process errors. But could you please explain what is Vinf_pp_hat and nd how do I get standard errors for the interaction matrix? Thank you!

**Comment by James-Thorson** [comment]
You can ignore Vinf_pp_hat (its the variance of the stationary distribution for the community, assuming that interactions are stable).

There should be an output from `Summarize` called `B_pp_hat_SE`, is that not there?

**Comment by MerjaElo** [comment]
Ok, thank you for the answer.

The output from Summarize does not contain B_pp_hat_SE, at least for me.

**Comment by James-Thorson** [comment]
If you look in the code for Summarize using `MIST::Summarize` in the R terminal, you'll see that it will only return `B_pp_hat_SE` if you pass the object `SD`.  Are you calling it using something like:

```R
parameter_estimates = TMBhelper::Optimize( ..., getsd=TRUE )
MIST::Summarize( ..., SD=parameter_estimates$SD )
```

i.e., where `parameter_estimates$SD` is the estimated standard errors?

**Comment by MerjaElo** [comment]
I called it incorrectly, thank you for clarifying!
